const axios = require("axios");
const fs = require('fs');
const scheduleScrapper = require("../../scraper/scheduleScrape");

jest.mock('axios');

test("TESTING: Schedule", async () => {  
  let schedule =     [
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'San Francisco Giants',
      away_code: 'sf',
      away_score: '0',
      away_record: '',
      home: 'Cincinnati Reds',
      home_code: 'cin',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T23:40:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354921'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Colorado Rockies',
      away_code: 'col',
      away_score: '0',
      away_record: '',
      home: 'Washington Nationals',
      home_code: 'wsh',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:05:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354912'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Baltimore Orioles',
      away_code: 'bal',
      away_score: '0',
      away_record: '',
      home: 'Boston Red Sox',
      home_code: 'bos',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:10:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354910'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Cleveland Guardians',
      away_code: 'cle',
      away_score: '0',
      away_record: '',
      home: 'Detroit Tigers',
      home_code: 'det',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:10:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354911'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'New York Yankees',
      away_code: 'nyy',
      away_score: '0',
      away_record: '',
      home: 'Tampa Bay Rays',
      home_code: 'tb',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:10:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354918'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Philadelphia Phillies',
      away_code: 'phi',
      away_score: '0',
      away_record: '',
      home: 'New York Mets',
      home_code: 'nym',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:10:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354919'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Miami Marlins',
      away_code: 'mia',
      away_score: '0',
      away_record: '',
      home: 'Atlanta Braves',
      home_code: 'atl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:20:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354916'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Kansas City Royals',
      away_code: 'kc',
      away_score: '0',
      away_record: '',
      home: 'Minnesota Twins',
      home_code: 'min',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T01:10:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354914'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Milwaukee Brewers',
      away_code: 'mil',
      away_score: '0',
      away_record: '',
      home: 'St Louis Cardinals',
      home_code: 'stl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T01:15:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354917'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Toronto Blue Jays',
      away_code: 'tor',
      away_score: '0',
      away_record: '',
      home: 'Los Angeles Angels',
      home_code: 'laa',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T02:38:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354923'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Houston Astros',
      away_code: 'hou',
      away_score: '0',
      away_record: '',
      home: 'Seattle Mariners',
      home_code: 'sea',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T02:40:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354913'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Los Angeles Dodgers',
      away_code: 'lad',
      away_score: '0',
      away_record: '',
      home: 'Arizona Diamondbacks',
      home_code: 'ari',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T02:40:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354915'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Pittsburgh Pirates',
      away_code: 'pit',
      away_score: '0',
      away_record: '',
      home: 'San Diego Padres',
      home_code: 'sd',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T02:40:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354920'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Texas Rangers',
      away_code: 'tex',
      away_score: '0',
      away_record: '',
      home: 'Oakland Athletics',
      home_code: 'oak',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T02:40:00.000Z"),
      date: new Date("2022-05-27T07:00:00.000Z"),
      gId: '401354922'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Baltimore Orioles',
      away_code: 'bal',
      away_score: '0',
      away_record: '',
      home: 'Boston Red Sox',
      home_code: 'bos',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T17:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401423224'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Kansas City Royals',
      away_code: 'kc',
      away_score: '0',
      away_record: '',
      home: 'Minnesota Twins',
      home_code: 'min',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T19:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354929'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Milwaukee Brewers',
      away_code: 'mil',
      away_score: '0',
      away_record: '',
      home: 'St Louis Cardinals',
      home_code: 'stl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T19:15:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354932'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Colorado Rockies',
      away_code: 'col',
      away_score: '0',
      away_record: '',
      home: 'Washington Nationals',
      home_code: 'wsh',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:05:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354927'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Texas Rangers',
      away_code: 'tex',
      away_score: '0',
      away_record: '',
      home: 'Oakland Athletics',
      home_code: 'oak',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:07:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354937'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Cleveland Guardians',
      away_code: 'cle',
      away_score: '0',
      away_record: '',
      home: 'Detroit Tigers',
      home_code: 'det',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354926'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Miami Marlins',
      away_code: 'mia',
      away_score: '0',
      away_record: '',
      home: 'Atlanta Braves',
      home_code: 'atl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354931'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'New York Yankees',
      away_code: 'nyy',
      away_score: '0',
      away_record: '',
      home: 'Tampa Bay Rays',
      home_code: 'tb',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354933'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'San Francisco Giants',
      away_code: 'sf',
      away_score: '0',
      away_record: '',
      home: 'Cincinnati Reds',
      home_code: 'cin',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354936'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Baltimore Orioles',
      away_code: 'bal',
      away_score: '0',
      away_record: '',
      home: 'Boston Red Sox',
      home_code: 'bos',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T23:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354924'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Chicago Cubs',
      away_code: 'chc',
      away_score: '0',
      away_record: '',
      home: 'Chicago White Sox',
      home_code: 'chw',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:15:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354925'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Los Angeles Dodgers',
      away_code: 'lad',
      away_score: '0',
      away_record: '',
      home: 'Arizona Diamondbacks',
      home_code: 'ari',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:15:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354930'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Philadelphia Phillies',
      away_code: 'phi',
      away_score: '0',
      away_record: '',
      home: 'New York Mets',
      home_code: 'nym',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:15:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354934'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Toronto Blue Jays',
      away_code: 'tor',
      away_score: '0',
      away_record: '',
      home: 'Los Angeles Angels',
      home_code: 'laa',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T03:07:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354938'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Houston Astros',
      away_code: 'hou',
      away_score: '0',
      away_record: '',
      home: 'Seattle Mariners',
      home_code: 'sea',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T03:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354928'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Pittsburgh Pirates',
      away_code: 'pit',
      away_score: '0',
      away_record: '',
      home: 'San Diego Padres',
      home_code: 'sd',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T03:10:00.000Z"),
      date: new Date("2022-05-28T07:00:00.000Z"),
      gId: '401354935'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'San Francisco Giants',
      away_code: 'sf',
      away_score: '0',
      away_record: '',
      home: 'Cincinnati Reds',
      home_code: 'cin',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T16:35:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354951'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Baltimore Orioles',
      away_code: 'bal',
      away_score: '0',
      away_record: '',
      home: 'Boston Red Sox',
      home_code: 'bos',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T18:35:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354939'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Colorado Rockies',
      away_code: 'col',
      away_score: '0',
      away_record: '',
      home: 'Washington Nationals',
      home_code: 'wsh',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T18:35:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354942'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Miami Marlins',
      away_code: 'mia',
      away_score: '0',
      away_record: '',
      home: 'Atlanta Braves',
      home_code: 'atl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T18:35:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354946'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Cleveland Guardians',
      away_code: 'cle',
      away_score: '0',
      away_record: '',
      home: 'Detroit Tigers',
      home_code: 'det',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T18:40:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354941'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'New York Yankees',
      away_code: 'nyy',
      away_score: '0',
      away_record: '',
      home: 'Tampa Bay Rays',
      home_code: 'tb',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T18:40:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354948'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Chicago Cubs',
      away_code: 'chc',
      away_score: '0',
      away_record: '',
      home: 'Chicago White Sox',
      home_code: 'chw',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T19:10:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354940'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Kansas City Royals',
      away_code: 'kc',
      away_score: '0',
      away_record: '',
      home: 'Minnesota Twins',
      home_code: 'min',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T19:10:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354944'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Milwaukee Brewers',
      away_code: 'mil',
      away_score: '0',
      away_record: '',
      home: 'St Louis Cardinals',
      home_code: 'stl',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T19:15:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354947'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Texas Rangers',
      away_code: 'tex',
      away_score: '0',
      away_record: '',
      home: 'Oakland Athletics',
      home_code: 'oak',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:07:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354952'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Toronto Blue Jays',
      away_code: 'tor',
      away_score: '0',
      away_record: '',
      home: 'Los Angeles Angels',
      home_code: 'laa',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:07:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354953'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Houston Astros',
      away_code: 'hou',
      away_score: '0',
      away_record: '',
      home: 'Seattle Mariners',
      home_code: 'sea',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354943'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Los Angeles Dodgers',
      away_code: 'lad',
      away_score: '0',
      away_record: '',
      home: 'Arizona Diamondbacks',
      home_code: 'ari',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354945'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Pittsburgh Pirates',
      away_code: 'pit',
      away_score: '0',
      away_record: '',
      home: 'San Diego Padres',
      home_code: 'sd',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-06T21:10:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354950'
    },
    {
      status: 0,
      clock: '',
      halftime: '',
      arena: '',
      currentQtr: '',
      maxQtr: '',
      away: 'Philadelphia Phillies',
      away_code: 'phi',
      away_score: '0',
      away_record: '',
      home: 'New York Mets',
      home_code: 'nym',
      home_score: '0',
      home_record: '',
      startTimeUTC: new Date("2022-05-07T00:00:00.000Z"),
      date: new Date("2022-05-29T07:00:00.000Z"),
      gId: '401354949'
    }
  ]
  axios.get.mockResolvedValue({ data: fs.readFileSync("./models/tests/html_tests/scheduleExample.html") });

  let scrapedSchedule= await scheduleScrapper.scrapeGames("mlb", "");
  expect(scrapedSchedule).toStrictEqual(schedule);
});